name: Build Android App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out the repository

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'  # Specify the Java version for your project

      - name: Build APK
        run: |
          chmod +x gradlew  # Make gradlew executable
          ./gradlew assembleRelease  # Build the APK in release mode

      - name: Upload APK
        uses: actions/upload-artifact@v2  # Uploads the generated APK as an artifact
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk  # Path to the generated APK
